### ISSUE TITLE
MODE_WORLD_READABLE no longer supported

### ISSUE THREAD

**Issue by pavlinux** [ant-wireless/ANT-Android-SDKs#19]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dsi.ant.antplus.pluginsampler/com.dsi.ant.antplus.pluginsampler.heartrate.Activity_AsyncScanHeartRateSampler}: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3304)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:221)
 at android.app.ActivityThread.main(ActivityThread.java:7520)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
 at android.app.ContextImpl.checkMode(ContextImpl.java:2636)
 at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:463)
 at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:453)
 at com.dsi.ant.plugins.utility.log.LogAnt.getDebugLevel(LogAnt.java:62)
 at com.dsi.ant.plugins.antplus.pccbase.AntPluginPcc.bindAndRequest(AntPluginPcc.java:579)
 at com.dsi.ant.plugins.antplus.pccbase.AntPluginPcc.requestAccess_Helper_SubMain(AntPluginPcc.java:558)
 at com.dsi.ant.plugins.antplus.pccbase.AntPluginPcc.requestAsyncScan_Helper_SubMain(AntPluginPcc.java:533)
 at com.dsi.ant.plugins.antplus.pccbase.AntPluginPcc.requestAccess_Helper_AsyncScanController(AntPluginPcc.java:437)
 at com.dsi.ant.plugins.antplus.pcc.AntPlusHeartRatePcc.requestAsyncScanController(AntPlusHeartRatePcc.java:521)
 at com.dsi.ant.antplus.pluginsampler.heartrate.Activity_AsyncScanHeartRateSampler.requestAccessToPcc(Activity_AsyncScanHeartRateSampler.java:144)
 at com.dsi.ant.antplus.pluginsampler.heartrate.Activity_HeartRateDisplayBase.handleReset(Activity_HeartRateDisplayBase.java:98)
 at com.dsi.ant.antplus.pluginsampler.heartrate.Activity_AsyncScanHeartRateSampler.handleReset(Activity_AsyncScanHeartRateSampler.java:218)
 at com.dsi.ant.antplus.pluginsampler.heartrate.Activity_HeartRateDisplayBase.onCreate(Activity_HeartRateDisplayBase.java:84)
 at com.dsi.ant.antplus.pluginsampler.heartrate.Activity_AsyncScanHeartRateSampler.onCreate(Activity_AsyncScanHeartRateSampler.java:51)
 at android.app.Activity.performCreate(Activity.java:7893)
 at android.app.Activity.performCreate(Activity.java:7880)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)

**Comment by pinicius** [comment]
What ant plugin lib version are using? With 3.8.0 version is fixed --> https://github.com/ant-wireless/ANT-Android-SDKs/issues/14

**Comment by harrychin** [comment]
It's not on the master branch right now, but you can find the latest version here:
https://github.com/ant-wireless/ANT-Android-SDKs/tree/development/C.B6-P.B6RC
