### ISSUE TITLE
INVALID_REQUEST for antChannel.setRfFrequency(57) with private NetworkKey

### ISSUE THREAD

**Issue by sh4wn** [ant-wireless/ANT-Android-SDKs#4]
```
...
mAntChannelProvider = ...
antChannel = mAntChannelProvider.acquireChannelOnPrivateNetwork(....)
antChannel.setRfFrequency(57)
```

**Comment by sh4wn** [comment]
The code i am using is the [Sample_BackgroundScan](https://github.com/ant-wireless/ANT-Android-SDKs/tree/master/ANT_Android_SDK/Sample_Applications/Sample_BackgroundScan).
Here is the stacktrace of that exception:

```
12-10 09:12:36.716: E/ChannelController(23118): com.dsi.ant.channel.AntCommandFailedException: ANT Service responded with failure reason: INVALID_REQUEST
12-10 09:12:36.716: E/ChannelController(23118):  at com.dsi.ant.channel.AntChannel.checkResult(AntChannel.java:895)
12-10 09:12:36.716: E/ChannelController(23118):  at com.dsi.ant.channel.AntChannel.setRfFrequency(AntChannel.java:349)
12-10 09:12:36.716: E/ChannelController(23118):  at com.dsi.ant.sample.backgroundscan.ChannelController.configureBackgroundScanningChannel(ChannelController.java:121)
12-10 09:12:36.716: E/ChannelController(23118):  at com.dsi.ant.sample.backgroundscan.ChannelController.<init>(ChannelController.java:86)
12-10 09:12:36.716: E/ChannelController(23118):  at com.dsi.ant.sample.backgroundscan.ChannelService.acquireBackgroundScanningChannel(ChannelService.java:244)
12-10 09:12:36.716: E/ChannelController(23118):  at com.dsi.ant.sample.backgroundscan.ChannelService$1.onServiceConnected(ChannelService.java:91)
12-10 09:12:36.716: E/ChannelController(23118):  at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1103)
12-10 09:12:36.716: E/ChannelController(23118):  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1120)
12-10 09:12:36.716: E/ChannelController(23118):  at android.os.Handler.handleCallback(Handler.java:733)
12-10 09:12:36.716: E/ChannelController(23118):  at android.os.Handler.dispatchMessage(Handler.java:95)
12-10 09:12:36.716: E/ChannelController(23118):  at android.os.Looper.loop(Looper.java:136)
12-10 09:12:36.716: E/ChannelController(23118):  at android.app.ActivityThread.main(ActivityThread.java:5113)
12-10 09:12:36.716: E/ChannelController(23118):  at java.lang.reflect.Method.invokeNative(Native Method)
12-10 09:12:36.716: E/ChannelController(23118):  at java.lang.reflect.Method.invoke(Method.java:515)
12-10 09:12:36.716: E/ChannelController(23118):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
12-10 09:12:36.716: E/ChannelController(23118):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
12-10 09:12:36.716: E/ChannelController(23118):  at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ANT-Shane** [comment]
As described in the API documentation https://www.thisisant.com/APIassets/Android_ANT_API/com/dsi/ant/channel/AntChannel.html#setRfFrequency(int):

> A frequency offset of 57 MHz (2457 MHz) is not allowed and is reserved for use by the ANT+ Plugin API, which must be used to connect to ANT+ devices.

Any network other than ANT+ should avoid using the frequency of 2057 to minimize interference and contention on that frequency. Refer to our forums for more discussion: https://www.thisisant.com/forum/viewthread/6364/

**Comment by sh4wn** [comment]
Thanks @ANT-Shane. I see it!
